"""The town art (factory/ui/town_art.py, generated by scripts/build_town.py): every piece draws, passes the layout's rules and stays inside the page policy."""
import json
import re
import unittest
from pathlib import Path

from factory.ui import flooredit, floorplan, terrain
from factory.ui.town_art import ART

STATIC = Path(terrain.__file__).parent / "static"


class TownTest(unittest.TestCase):
    def test_every_piece_is_a_park_piece_with_a_box_a_name_and_a_tool(self):
        tools = {t for _, ts in flooredit.TERRAIN_TOOLS for t, _ in ts}
        self.assertEqual(len(ART), 55)
        for kind, a in ART.items():
            self.assertIn(kind, terrain.KINDS)
            self.assertIn(kind, terrain.SOLID)
            self.assertEqual(terrain.PARK[kind], (a["w"], a["h"]))
            self.assertIn(kind, tools)

    def test_a_piece_draws_in_its_box_with_no_style_attribute(self):
        for kind, a in ART.items():
            svg = terrain.svg({"items": [[kind, 400, 300, a["w"], 1], [kind, 800, 300, a["w"], 2]]}, 20, 1200, 600, layer="over")
            self.assertIn('class="tw-art"', svg)
            self.assertNotIn("style=", svg, kind)

    def test_every_class_the_art_uses_is_in_the_stylesheet(self):
        css = (STATIC / "town.css").read_text()
        for kind, a in ART.items():
            for c in {c for v in re.findall(r'class="([^"]+)"', a["svg"]) for c in v.split()}:
                self.assertIn("." + c, css, f"{kind}: {c}")

    def test_the_editor_gets_the_same_art(self):
        js = (STATIC / "town.js").read_text()
        self.assertEqual(json.loads(js[js.index("{"):js.rindex("}") + 1]), ART)

    def test_the_motion_stops_for_people_who_ask_for_less(self):
        self.assertIn("prefers-reduced-motion:reduce", (STATIC / "town.css").read_text())


if __name__ == "__main__":
    unittest.main()
